framework:
    cache:
        app: cache.adapter.redis
        default_redis_provider: '%env(REDIS_URL)%'
        
        pools:
            account.cache:
                adapter: cache.adapter.redis
                provider: '%env(REDIS_URL)%'
            transfer.lock:
                adapter: cache.adapter.redis
                provider: '%env(REDIS_URL)%'
            # Doctrine cache pools
            doctrine.result_cache_pool:
                adapter: cache.adapter.redis
                provider: '%env(REDIS_URL)%'
            doctrine.system_cache_pool:
                adapter: cache.adapter.redis
                provider: '%env(REDIS_URL)%'
            doctrine.query_cache_pool:
                adapter: cache.adapter.redis
                provider: '%env(REDIS_URL)%'
